# Your list of prompts as a string. I've shortened it for the example.
raw_prompts = '''
"A cosmic map with stars highlighting Dhanishta, pulsating to a drum's beat",
    "Zodiac wheel with Capricorn and Aquarius glowing, a drum in their centers",
    "A celestial drum hanging in space, meteors acting as drumsticks",
    "Drumsticks hitting a cosmic drum, each beat emitting a pulse of light",
    "Stars and planets dancing to a celestial drumbeat in the shape of a dance floor",
    "Drum morphing into an infinity symbol, surrounded by time clocks",
    "Drum at the center of a life-death cycle spiral",
    "A drum with yin-yang symbols as drum skins, rotating",
    "Human figures drawn to a cosmic drum, like planets to a sun",
    "Veins on a human arm pulsating to the rhythm of a drumbeat",
    "Cosmic influencer selfie, but the phone is a drum that radiates light",
    "Human radiating light, words like 'abundance' and 'fame' circling",
    "Celestial DJ booth with a drum, stars dancing around it",
    "Musical notes turning into mini drums as they float in space",
    "Talent show stage with performer, drum-shaped spotlight on them",
    "Elemental gods, each holding a tiny drum, merging into a single deity",
    "Eight elemental Vasus styled like Captain Planet, drum hovering above",
    "Person meditating, elemental symbols circling them, drum in center",
    "Eight Vasus channeling energy into a drum, which then lights up a human",
    "Person using elemental powers, each power emitting from a mini drum",
    "Climate march leader holding a drum, crowd following the beat",
    "Artist painting a social justice mural, drum-shaped paint palette",
    "Scientist with eco-tech, a drum-shaped eco gadget on the table",
    "Social media feed with drum icons, promoting various good causes",
    "Earth radios playing cosmic playlist, each radio shaped like a drum",
    "Ancient scroll unrolls, revealing drum symbols along with Dhanishta texts",
    "Moon traveling in the sky, a drum-shaped shadow over it",
    "Cosmic calendar with drum-shaped dates circled in light",
    "Astrologer with celestial map, drum constellation glowing",
    "Newborn surrounded by glowing drum-shaped celestial bodies",
    "Drum transforming into Earth, continents shaped like musical notes",
    "Celestial beings, each with a drum, playing in harmony",
    "Drumsticks made of pure energy striking a glowing drum",
    "Drum resonating, sending vibrations to other celestial bodies",
    "Drum transforming into a beating heart, veins pulsating",
    "Drum glowing brighter as words like 'wealth' and 'success' spiral into it",
    "Marilyn Monroe singing, a drum-shaped spotlight illuminating her",
    "Ashton Kutcher accepting an award, drum-shaped trophy",
    "Symphony sheet music, but the notes are tiny drum symbols",
    "Drum-shaped social media like button, racking up likes",
    "Elemental gods blessing Earth, each god holding a tiny drum",
    "Meditating figure, transforming into a Vasu, holding a drum",
    "Ritual altar, eight Vasus represented by eight different drums",
    "Vasus appearing in a dream, teaching how to play a celestial drum",
    "Person offering prayers, incense smoke forming drum shapes",
    "Person reciting poetry at a social gathering, drum in the background",
    "Volunteers planting trees, each seed in the shape of a tiny drum",
    "Eco-friendly start-up office, drum-shaped eco gadgets everywhere",
    "Courtroom scene, judge's gavel shaped like a drum",
    "Global meditation event, drum-shaped earth glowing in peace",
    "Earth spinning to the rhythm of a cosmic drumbeat",
    "Multiple generations, each holding a drum, dancing in a circle",
    "Teacher instructing students to find their rhythm, using drums",
    "Cosmic jukebox, each selection button shaped like a drum",
    "Drum-shaped compass pointing to the words 'life purpose'",
    "Clock hands moving to the beat of a drum, synchronizing",
    "Planetary alignment forming a drum shape",
    "Astrological chart, Dhanishta area glowing and pulsating",
    "Classroom scene, teacher pointing to a drum on the blackboard",
    "Library scene, all books shaped like drums on the shelves",
    "Drum radiating pure energy, forming an aura",
    "Celestial orchestra, all instruments morphing into drums",
    "Human channeling energy into a drum from their heart",
    "Drum transforming into a spiral galaxy",
    "Drum and heartbeat synced, visualized on a monitor",
    "Honorary degree being handed to a person, drum-shaped certificate",
    "Grammy Awards stage, drum-shaped Grammy statue",
    "Trophy case, all trophies shaped like drums",
    '"Dhanishta" hashtag trending, each tweet symbolized by a drum',
    "Person radiating light among a crowd, drum-shaped aura",
    "Vasus guiding a person through a forest, each tree resembling a drum",
    "Person drawing elemental symbols, each one morphing into a drum",
    "Vasus appearing in a cloud formation, each cloud shaped like a drum",
    "Vasus discussing around a table, each seat resembling a drum",
    "Person lighting drum-shaped candles in a spiritual ritual",
    "Person donating to charity, coins morphing into tiny drums",
    "TV interview, drum-shaped microphones",
    "Community garden, each plant pot shaped like a drum",
    "Best-selling spiritual book, cover shaped like a drum",
    "Nobel Prize ceremony, drum-shaped Nobel medal",
    "DJ at a cosmic party, all controls shaped like drums",
    "Two people finding soulmates, hearts morphing into drums",
    "Song uniting the world, each speaker emitting drum-shaped sound waves",
    "Globe vibrating, each continent pulsating like a drum skin",
    "Person listening to cosmic beats on drum-shaped headphones",
    "Marilyn Monroe in her iconic pose, but holding a drum",
    "Ashton Kutcher in a tech lab, working on a drum-shaped computer",
    "Marilyn Monroe and Ashton Kutcher in a cosmic dance, each holding a drum",
    "Ashton Kutcher in a 'Punk’d' scene, but the prank reveal is a drum",
    "Marilyn Monroe in a movie scene, dramatically singing into a drum-shaped microphone",
    "A spaceship shaped like a drum traveling through space",
    "A drum transforming into a celestial phoenix",
    "Drum-shaped island in the middle of the ocean",
    "A drum-shaped maze, person navigating through it",
    "A drum beating to the rhythm of falling rain",
    "A drum-shaped sun rising over a mountain",
    "An old wise man telling stories, a drum beside him",
    "A baby's first word visualized as a drum symbol",
    "A drum-shaped moon reflecting on a tranquil lake",
    "A drum as the centerpiece of a cosmic mandala",
'''

# Split the string into a list of prompts, then strip away the quotes and extra commas
cleaned_prompts = [prompt.strip('"').replace(", ", " ") for prompt in raw_prompts.strip().split(",\n")]

# Join them back into a single string separated by commas
cleaned_prompts_str = ", ".join(cleaned_prompts)

print(cleaned_prompts_str)
